# Project: HW
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = temp/debug/main.o
LINKOBJ  = temp/debug/main.o
LIBS     = -L"C:/Users/날큂/Desktop/DevCppPortable/MinGW64/lib" -L"C:/Users/날큂/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/날큂/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/날큂/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/날큂/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/날큂/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/날큂/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/날큂/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/날큂/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = temp/debug/HW.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

temp/debug/main.o: temp/debug/main.c
	$(CC) -c temp/debug/main.c -o temp/debug/main.o $(CFLAGS)
